package com.netsdk.lib.enumeration;

public enum EM_FACE_TRAIT_EMOTION_TYPE {
    EM_FACE_TRAIT_EMOTION_UNKNOWN,					// 未知
    EM_FACE_TRAIT_EMOTION_UNRECOGNIZE,				// 未识别
    EM_FACE_TRAIT_EMOTION_ANGRY,					// 生气
    EM_FACE_TRAIT_EMOTION_SAD,						// 悲伤
    EM_FACE_TRAIT_EMOTION_DISGUST,					// 厌恶
    EM_FACE_TRAIT_EMOTION_FEAR,						// 恐惧
    EM_FACE_TRAIT_EMOTION_SURPRISE,					// 诧异
    EM_FACE_TRAIT_EMOTION_CALM,						// 平静
    EM_FACE_TRAIT_EMOTION_SMILE,					// 微笑
    EM_FACE_TRAIT_EMOTION_LAUGH,					// 大笑
    EM_FACE_TRAIT_EMOTION_HAPPY,					// 高兴
    EM_FACE_TRAIT_EMOTION_CONFUSED,					// 困惑
    EM_FACE_TRAIT_EMOTION_SCREAM,					// 尖叫
}
