package com.netsdk.lib.enumeration;
/** 逻辑屏背景风格模式  */
public enum NET_EM_LATTICE_SCREEN_BACKGROUND_MODE {

    NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_UNKNOWN,				// 未知
    NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_A,					// 背景风格A
    NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_B,					// 背景风格B
    NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_C,					// 背景风格C

}
